tPerProfile = {
	[5] = {
		["Minshare"] = 0,
		["Minslots"] = 0,
		["RHubs"] = 0,
		["RSlots"] = 0,
		["Maxslots"] = 0,
		["Maxshare"] = 0,
	},
	[1] = {
		["Minshare"] = 0,
		["Minslots"] = 0,
		["RHubs"] = 0,
		["RSlots"] = 0,
		["Maxslots"] = 0,
		["Maxshare"] = 0,
	},
	[-1] = {
		["Minshare"] = 0,
		["Minslots"] = 0,
		["RHubs"] = 0,
		["RSlots"] = 0,
		["Maxslots"] = 0,
		["Maxshare"] = 0,
	},
	[2] = {
		["Minshare"] = 0,
		["Minslots"] = 0,
		["RHubs"] = 0,
		["RSlots"] = 0,
		["Maxslots"] = 0,
		["Maxshare"] = 0,
	},
	[0] = {
		["Minshare"] = 0,
		["Minslots"] = 0,
		["RHubs"] = 0,
		["RSlots"] = 0,
		["Maxslots"] = 0,
		["Maxshare"] = 0,
	},
	[3] = {
		["Minshare"] = 0,
		["Minslots"] = 0,
		["RHubs"] = 0,
		["RSlots"] = 0,
		["Maxslots"] = 0,
		["Maxshare"] = 0,
	},
	[4] = {
		["Minshare"] = 0,
		["Minslots"] = 0,
		["RHubs"] = 0,
		["RSlots"] = 0,
		["Maxslots"] = 0,
		["Maxshare"] = 0,
	},
	[6] = {
		["Minshare"] = 0,
		["Minslots"] = 0,
		["RHubs"] = 0,
		["RSlots"] = 0,
		["Maxslots"] = 0,
		["Maxshare"] = 0,
	},
}