tEightBall = {
	["Bot"] = "[Eight-Ball]",
	["Reply"] = {
		[5] = {
			["Count"] = 1,
			["Reply"] = "What? Sorry I haven't paid attention, ask again...",
		},
		[9] = {
			["Count"] = 2,
			["Reply"] = "Blah blahhh blahh...",
		},
		[3] = {
			["Count"] = 2,
			["Reply"] = "Yes.",
		},
	},
	["Time"] = 5,
	["Answers"] = {
		[27] = "What? Sorry I haven't paid attention, ask again...",
		[2] = "Yes.",
		[38] = "Get a life and leave me alone!",
		[3] = "NOOOOOOOOOOOOOOOOOOO!",
		[4] = "Definitely.",
		[5] = "All signs point to yes.",
		[6] = "Yeah :)",
		[7] = "HELL NO!",
		[8] = "No way my friend!",
		[39] = "BLOOD SHALL COME UPON YOU!",
		[12] = "Without a doubt!",
		[14] = "You may rely on it.",
		[16] = "My sources say no...",
		[20] = "Better not tell you know ;-)",
		[24] = "Pay me and I'm gonna tell you.",
		[28] = "Huh?",
		[32] = "Haha, I like you...funny guy, you are :-)",
		[40] = "Get some money first.",
		[33] = "Geeeeee...what a stupid question.",
		[41] = "Yes, #NICK#. I believe so :-)",
		[17] = "Yes, most likely.",
		[21] = "Couldn't read from brain. (A)bort, (R)etry, (I)gnore?_",
		[25] = "Ask your mummy, she knows better than a stupid billard ball!",
		[29] = "Blah blahhh blahh...",
		[34] = "Stop doing drugs :-P",
		[42] = "I don't know, #NICK#?! What do you think?",
		[9] = "Never ever.",
		[11] = "Don't count on it.",
		[13] = "My reply is no.",
		[15] = "I can't predict now, need some food first!",
		[18] = "Concentrate and ask again.",
		[22] = "I calculated the probability to 50 percent.",
		[26] = "Are you kidding?",
		[30] = "You must be kidding!",
		[36] = "How should I know?",
		[44] = "Are you on drugs?",
		[43] = "Who cares?? Try to think of a better question, #NICK#!",
		[31] = "Are you serious?",
		[37] = "And they say there are no stupid questions...",
		[45] = "I don't know.. Ask Snooze :-)",
		[10] = "As certain as death!",
		[1] = "No.",
		[19] = "This is very doubtful.",
		[23] = "I know but I won't tell you :-)",
		[35] = "How could you think of such things?",
	},
}