tCoreConfig = {
	["Modules"] = {
		["Userfunc"] = true,
		["Chats"] = true,
		["Anagram"] = true,
		["Stats"] = true,
		["Trivia"] = true,
		["Texter"] = true,
		["Poll"] = true,
		["Numbers"] = true,
		["RussRoul"] = true,
		["AutoUpdate"] = false,
		["TimedMsg"] = true,
		["Motd"] = true,
		["Regcleaner"] = true,
		["Rules"] = true,
		["Logger"] = true,
		["HubConfig"] = true,
		["Tophubber"] = true,
		["ReqRel"] = true,
		["Trigger"] = true,
		["CustomReg"] = true,
		["DxbCore"] = true,
		["Blocker"] = true,
		["Antiadv"] = true,
		["ChatHist"] = true,
		["DxbBackup"] = true,
		["EightBall"] = true,
		["Opfunc"] = true,
		["WordReplace"] = true,
		["Greeting"] = false,
		["Mailbox"] = true,
	},
	["TxtFiles"] = {
	},
	["System"] = {
		["wPath"] = "C:/Users/sreer/Downloads/PtokaX 0.5.2.1 with Lua 5.1.5 + DiXBoTv2.1 Build 3080/MyHub/MyHub/scripts/",
		["OS"] = "Windows",
		["Rightclick"] = true,
		["Mail"] = "dixbot@dixbot.com",
		["WebSite"] = "zcultfm.com",
		["Prefix"] = {
			["!"] = 1,
			["+"] = 1,
			["-"] = 1,
			["§"] = 1,
			["/"] = 1,
		},
	},
}